services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: ragchat-frontend-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped
