version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app/current
    overwrite: true
hooks:
  ApplicationStop:
    - location: deploy/scripts/stop.sh
      timeout: 180
      runas: root
  BeforeInstall:
    - location: deploy/scripts/install.sh
      timeout: 1800
      runas: root
  ApplicationStart:
    - location: deploy/scripts/start.sh
      timeout: 300
      runas: root
